name: "Tesla CPO Inventory Monitor"
version: "0.0.74"
slug: "tesla_cpo_inventory_tracker"
description: "Monitors Tesla CPO inventory for specific VIN(s)"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  market: str
  region: str
  language: str
  postalCode: str
  models: 
    - "Model S"
    - "Model 3"
    - "Model X"
    - "Model Y"
    - "Cybertruck"
  vins: null
  interval: 15
  devices_to_notify: null
  test_notification: false
schema:
  market: str
  region: str
  language: str
  postalCode: str
  models:
    - str
  vins:
    - str
  interval: int(1,20)
  devices_to_notify:
    - str
  test_notification: bool
url: "https://github.com/mwood77/ha-tesla-inventory-tracker"
icon: mdi:car-arrow-right

stage: stable
ingress: false
hassio_api: true
hassio_role: default
homeassistant_api: true
homeassistant: true
host_network: true
auth_api: true
