name: "Tesla CPO Inventory Monitor"
version: "0.0.46"
slug: "tesla_cpo_inventory_tracker"
description: "Monitors Tesla CPO inventory for specific VIN(s)"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  vins: 
    - LRW3E7EL3PC666768
  interval: 1
  devices_to_notify: 
    - mobile_app_mick_iphone
    - mobile_app_wood_ipad
  test_notification: false
schema:
  vins:
    - str
  interval: int(1,20)
  devices_to_notify:
    - str
  test_notification: bool
url: "https://github.com/mwood77/ha-tesla-inventory-tracker"
icon: mdi:car-arrow-right

stage: stable
ingress: false
hassio_api: true
hassio_role: default
homeassistant_api: true
homeassistant: true
host_network: true
auth_api: true