name: Lint Project

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ha-tesla-inventory-tracker/.nvmrc

      - name: Install Node.js dependencies
        working-directory: ha-tesla-inventory-tracker
        run: npm ci

      - name: Lint Action
        uses: rkuykendall/lint-action@master
        with:
          eslint: true
          prettier: true
